gestao_dh/urls.py
from django.contrib import admin
from django.urls import path, include  # Importe a função include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('artista.urls')),  # Inclua as URLs do aplicativo artista
    # Adicione outras URLs conforme necessário
]

urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),  # URL para a página inicial
    path('cadastrar-artista/', views.cadastrar_artista, name='cadastrar_artista'), #URL para a pág. de cadastro de artista
    path('listar-artista/', views.listar_artista, name='listar_artista'), #URL para listar os artistas.
    path('editar-artista/<int:artista_id>/', views.editar_artista, name='editar_artista'),  #URL para editar o artista.
    path('excluir-artista/<int:artista_id>/', views.excluir_artista, name='excluir_artista'), #URL para excluir o artista.
    path('confirmar-excluir-artista/<int:artista_id>/', views.confirmar_excluir_artista, name='confirmar_excluir_artista'), 
    path('sem_artista/', views.sem_artista, name='sem_artista'),
    path('listar_eventos/', views.listar_eventos, name='listar_eventos'),
    path('criar_evento/', views.criar_evento, name='criar_evento'),
]
 

models.py
from datetime import datetime
from django.db import models
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator, EmailValidator
from validate_docbr import CPF # type: ignore
from django.utils.translation import gettext_lazy as _

# Lista de opções de tipo de chave PIX
TIPO_CHAVE_CHOICES = [
    ('cel', 'Celular'),
    ('cnpj', 'CNPJ'),
    ('email', 'E-mail'),
    ('cpf', 'CPF'),
]

# Aqui vão as definições de modelos existentes, como Artista, etc.

def validar_cpf(value):
    cpf_validator = CPF()
    if not cpf_validator.validate(value):
        raise ValidationError('CPF inválido.')


def validar_chave_pix(value, tipo_chave):
    if tipo_chave == 'cel':  # Verifica se a chave PIX é um número de celular
        if len(value) != 11 or not value.isdigit():
            raise ValidationError('O número de celular deve conter exatamente 11 dígitos numéricos.')
    elif tipo_chave == 'cnpj':  # Verifica se a chave PIX é um CNPJ
        if len(value) != 14 or not value.isdigit():
            raise ValidationError('O CNPJ deve conter exatamente 14 dígitos numéricos.')
    elif tipo_chave == 'email':  # Verifica se a chave PIX é um e-mail
        validator = EmailValidator(message='O e-mail fornecido não é válido.')
        validator(value)
    else:
        raise ValidationError('Tipo de chave PIX inválido.')
    
def validar_horario(value):
    # Verifica se o horário é '24:00' horas
    if value.hour == 0 and value.minute == 0:
        return
    # Verifica se o horário está dentro do intervalo válido (por exemplo, entre 00:00 e 23:59)
    if value < datetime.time(0, 0) or value > datetime.time(23, 59):
        raise ValidationError('Horário inválido. O horário deve estar entre 00:00 e 23:59.')
    
class Artista(models.Model):
    nome = models.CharField(max_length=100, null=False, blank=False)
    cpf = models.CharField(max_length=11, unique=True, validators=[validar_cpf])
    telefone = models.CharField(max_length=15, null=True)
    banco = models.CharField(max_length=100, null=True)  #instituição bancária
    tipo_chave_pix = models.CharField(max_length=10, choices=TIPO_CHAVE_CHOICES, default='cel')
    chave_pix = models.CharField(max_length=100)
    
    def clean(self):
        validar_chave_pix(self.chave_pix, self.tipo_chave_pix)

    def __str__(self):
        return self.nome

class Evento(models.Model):
    artista = models.ForeignKey(Artista, on_delete=models.CASCADE)
    data = models.DateField()
    horario = models.TimeField(validators=[validar_horario])
    
    def __str__(self):
        return self.artista.nome if self.artista else 'Evento sem artista'
    # Adicione outros campos relevantes para os eventos, se necessário

     

forms.py
from django import forms
from .models import Artista, Evento
from .widgets import CustomDateInput
class ArtistaForm(forms.ModelForm):
    class Meta:
        model = Artista
        fields = '__all__'  # Utilize '__all__' para incluir todos os campos do modelo no formulário
        
class CustomDateInput(forms.DateInput):
    input_type = 'text'

    def __init__(self, attrs=None, format='%d-%m-%y'):
        super().__init__(attrs=attrs, format=format)

    def format_value(self, value):
        if isinstance(value, str):
            return value
        return value.strftime('%d-%m-%y') if value else ''


class EventoForm(forms.ModelForm):
    data = forms.DateField(widget=CustomDateInput, input_formats=['%d-%m-%Y', '%d-%m-%y'])
    horario = forms.TimeField(widget=forms.TimeInput(format='%H:%M'))
    class Meta:
        model = Evento
        fields = ['artista', 'data', 'horario']
        
    

views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from .models import Artista
from .forms import ArtistaForm
from .models import Evento
from .forms import EventoForm


def home(request):
    # Adicione qualquer lógica necessária aqui
    return render(request, 'artista/home.html')


def cadastrar_artista(request):
    if request.method == 'POST':
        form = ArtistaForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Artista cadastrado com sucesso!')
            form = ArtistaForm()
            # Redirecionar o usuário para outra página, se necessário
    else:
        form = ArtistaForm()
    return render(request, 'artista/cadastrar_artista.html', {'form': form})


def listar_artista(request):
    artistas = Artista.objects.all()
    if not artistas:
        return render(request, 'artista/sem_artista.html')
    else:
        return render(request, 'artista/listar_artista.html', {'artistas': artistas})


def sem_artista(request):
    return render(request, 'artista/sem_artista.html')


def editar_artista(request, artista_id):
    artista = get_object_or_404(Artista, pk=artista_id)
    if request.method == 'POST':
        form = ArtistaForm(request.POST, instance=artista)
        if form.is_valid():
            form.save()
            messages.success(request, 'Artista editado com sucesso!')
            return redirect('listar_artista')
        else:
            messages.error(request, 'Corrija os erros no formulário.')
    else:
        form = ArtistaForm(instance=artista)
    return render(request, 'editar_artista.html', {'form': form, 'artista': artista})


def excluir_artista(request, artista_id):
    artista = get_object_or_404(Artista, pk=artista_id)
    if request.method == 'POST':
        artista.delete()
        messages.success(request, 'Artista excluído com sucesso!')
        return redirect('listar_artista')
    return render(request, 'artista/excluir_artista_confirmacao.html', {'artista': artista})


def confirmar_excluir_artista(request, artista_id):
    # Recuperar o objeto do artista a ser excluído
    artista = get_object_or_404(Artista, pk=artista_id)
    # Renderizar o template com o contexto adequado
    return render(request, 'artista/excluir_artista_confirmacao.html', {'artista': artista})


def listar_eventos(request):
    eventos = Evento.objects.all()
    return render(request, 'artista/listar_eventos.html', {'eventos': eventos})


def criar_evento(request):
    if request.method == 'POST':
        form = EventoForm(request.POST)
        if form.is_valid():
            evento = form.save()
            print("Evento salvo com sucesso:", evento)
            return redirect('artista/listar_eventos')
        else:
            print("Erros no formulário:", form.errors)
    else:
        form = EventoForm()
    return render(request, 'artista/criar_evento.html', {'form': form})

templates/artista/base.html
<!--Este arquivo representa o modelo base para todas as páginas do seu aplicativo. Ele define a estrutura básica do HTML, incluindo o cabeçalho, navegação, conteúdo principal e rodapé. O conteúdo específico de cada página será inserido aqui-->
<!doctype html>
<html lang="pt-br">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Gestão Dh</title>
</head>

<body>
    <nav style="background-color: green !important;" class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <span class="navbar-brand mb-0 h1">Gestão Dh</span> 
        </div>
    </nav>

    {% if messages %}
        <div class="container">
            <div class="alert alert-dismissible {% if message.tags %} alert-{{ message.tags }}{% endif %}" role="alert">
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
            </div>
        </div>
    {% endif %}

    <div class="container">
        {% block conteudo %}

        {% endblock %}
    </div>
    
    
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
</body>

</html>

templates/artista/cadastrar_artista.html
{% extends 'artista/base.html' %}
{% block conteudo %}
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <title>Cadastrar Artista</title>
</head>
<body>
    <h1>Cadastrar Novo Artista</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">salvar</button>  
        <a href="{% url 'home' %}">Voltar</a>      
    </form>
    
    

</body>
</html>
{% endblock %}

templates/artista/criar_evento.html
<!-- criar_evento.html -->
{% extends 'artista/base.html' %}
{% block conteudo %}
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <title>Criar Evento</title>
    </script>
    <!--Formatando data para: (dd-mm-yyyy)-->
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
    <!--Formatando horas para: (hh:mm)-->
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.13.18/jquery.timepicker.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.13.18/jquery.timepicker.min.js"></script>
    <script src="{% static 'evento.js' %}"></script> <!-- Arquivo JavaScript externo -->
</head>

<body>
    <h1>Criar Evento</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Salvar</button>
        <a href="{% url 'home' %}"><button type="button">Voltar</button></a>
    </form>

    <script>
        $(function () {
            $("#id_data").datepicker({ dateFormat: 'dd-mm-yy' });
        });
    </script>
    <script>
        $(function () {
            $('#id_horario').timepicker({
                timeFormat: 'H:Hm',
                interval: 15, // intervalo de 15 minutos,
                scrollbar: true, // exibir barra de rolagem para selecionar horas
                dropdown: true, // permitir menu para selecionar horas
                onSelect: function (timeText, inst) {
                    $('#id_horario').val(timeText); // atribui o novo valor de hora selecionado ao campo de entrada
                }
            });

        });
    </script>
</body >
</html >
{% endblock %}

templates/artista/editar_artista.html
<!-- templates/artista/editar_artista.html -->
{% extends 'artista/base.html' %}

{% block conteudo %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Editar Artista</title>
</head>
<body>
    <h1>Editar Artista</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Salvar</button>
        <button type="submit">Voltar</button>
    </form>
</body>
</html>
{% endblock %}

templates/artista/excluir_artista_confirmacao.html
{% extends 'artista/base.html' %}

{% block conteudo %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Confirmação de Exclusão</title>
</head>
<body>
    <h1>Confirmação de Exclusão</h1>
    <p>Você tem certeza de que deseja excluir o artista "{{ artista.nome }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Sim, Excluir</button>
        <a href="{% url 'listar_artista' %}">Cancelar</a>
    </form>
</body>
</html>
{% endblock %}

templates/artista/home.html
<!-- templates/artista/home.html -->
{% extends 'artista/base.html' %}
{% block conteudo %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Gestão DH</title>
</head>
<body>
    <h1>Casting Artístico DH PRODUÇÕES</h1>
    <a href="{% url 'cadastrar_artista' %}"class="btn btn-primary">Cadastrar Novo Artista</a>
    <a href="{% url 'listar_artista' %}" class="btn btn-primary">Listar Artistas</a>
    <a href="{% url 'criar_evento' %}" class="btn btn-primary">Criar Evento</a>
    <a href="{% url 'listar_eventos' %}" class="btn btn-primary">Listar Eventos</a>
   
    <!-- Adicione qualquer conteúdo desejado para a página inicial -->
</body>
</html>
{% endblock %}

templates/artista/listar_artista.html
<!-- templates/artista/listar_artistas.html -->

{% extends 'artista/base.html' %}

{% block conteudo %}
  <h1>Lista de Artistas</h1>

  {% if artistas %}
    <table>
      <thead>
        <tr>
          <th>ID</th>
          <th>Nome</th>
          <th>CPF</th>
          <th>Tipo de Chave PIX</th>
          <th>Chave PIX</th>
          <th>Banco</th>
          <th>Ações</th>
        </tr>
      </thead>
      <tbody>
        {% for artista in artistas %}
          <tr>
            <td>{{ artista.id }}</td>
            <td>{{ artista.nome }}</td>
            <td>{{ artista.cpf }}</td>
            <td>{{ artista.tipo_chave_pix }}</td>
            <td>{{ artista.chave_pix }}</td>
            <td>{{ artista.Banco }}</td>
            <td><a href="{% url 'editar_artista' artista.id %}">Editar</a></td> <!-- Link para editar o artista -->
            <td><a href="{% url 'excluir_artista' artista.id %}">Excluir</a></td>
          </tr>
        {% endfor %}
      </tbody>
            
    </table>
            <a href="{% url 'home' %}">Voltar</a>
  {% else %}
    <p>Nenhum artista cadastrado.</p>
  {% endif %}
{% endblock %}

templates/artista/listar_eventos.html
<!-- listar_eventos.html -->
{% extends 'artista/base.html' %}
{% block conteudo %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Listar Eventos</title>
</head>
<body>
    <h1>Eventos</h1>
    {% if eventos %}
        <ul>
            {% for evento in eventos %}
                <li>{{ evento }}</li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Não há eventos cadastrados.</p>
    {% endif %}

    <a href="{% url 'criar_evento' %}">Criar Novo Evento</a>
    <a href="{% url 'criar_evento' %}">Voltar</a>
</body>
</html>
{% endblock %}

templates/artista/sem_artista.html
{% extends 'artista/base.html' %}
{% block conteudo %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sem Artistas</title>
</head>
<body>
    <h1>Nenhum artista cadastrado</h1>
    <p>Não há artistas cadastrados no momento.</p>
    <a href="{% url 'home' %}">Voltar</a>
    <!-- Aqui você pode adicionar qualquer mensagem adicional que desejar -->
</body>
</html>
{% endblock %}